# What is NumPy

In [4]:
# NumPy is a Python library.
# NumPy is used for working with arrays.
# NumPy is short for "Numerical Python".

In [5]:
# NumPy is a Python library used for working with arrays.
# It also has functions for working in domain of linear algebra, fourier transform, and matrices.
# NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

# Why Use NumPy?

In [6]:
# In Python we have lists that serve the purpose of arrays, but they are slow to process.
# NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

# Which Language is NumPy written in?

In [7]:
# NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.

# Import NumPy

In [8]:
# Once NumPy is installed, import it in your applications by adding the import keyword:

In [9]:
import numpy

In [10]:
import numpy

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


# NumPy as np

In [11]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


# Checking NumPy Version

In [12]:
import numpy as np

print(np.__version__)

1.21.5


# NumPy Creating Arrays

In [14]:
import numpy as np
arr= np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# Dimensions in Arrays

In [15]:
# 0-D Arrays

In [16]:
# 0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [17]:
import numpy as np
arr=np.array(42)
print(arr)

42


In [18]:
# 1-D Arrays

In [19]:
# An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

In [20]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [21]:
# 2-D Arrays

In [22]:
# An array that has 1-D arrays as its elements is called a 2-D array.

In [23]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [24]:
# 3-D arrayy

In [25]:
# An array that has 2-D arrays (matrices) as its elements is called 3-D array.

In [26]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


# Check Number of Dimensions

In [28]:
# NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.


import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [29]:
# An array can have any number of dimensions.

In [32]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)

[[[[[1 2 3 4]]]]]


In [33]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=4)

print(arr)

[[[[1 2 3 4]]]]


# NumPy Array Indexing

In [34]:
# Array indexing is the same as accessing an array element.
# You can access an array element by referring to its index number.

In [35]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [36]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[1])

2


In [37]:
# Access 2-D Arrays

In [38]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [39]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


In [40]:
# Access 3-D Arrays

In [41]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


In [42]:
# Negative Indexing

In [43]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])


Last element from 2nd dim:  10


# NumPy Array Slicing

In [44]:
# Slicing in python means taking elements from one given index to another given index.

# We pass slice instead of index like this: [start:end].

In [45]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [46]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


In [47]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


In [48]:
# Negative Slicing

In [49]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [50]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [51]:
# Slicing 2-D Arrays


In [52]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [53]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


# NumPy Data Types

In [54]:
# NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

In [55]:
# i - integer
# b - boolean
# u - unsigned integer
# f - float
# c - complex float
# m - timedelta
# M - datetime
# O - object
# S - string
# U - unicode string
# V - fixed chunk of memory for other type ( void )

In [56]:
# Checking the Data Type of an Array

In [57]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [58]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [59]:
# Creating Arrays With a Defined Data Type
# We use the array() function to create arrays, this function can take an optional argument: dtype that allows us to define the expected data type of the array elements:

In [61]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [62]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


# NumPy Array Copy vs View

In [63]:
# The Difference Between Copy and View
# The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

# The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

# The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [64]:
# COPY

In [65]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [66]:
# VIEW

In [67]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


# NumPy Array Shape

In [1]:
# The shape of an array is the number of elements in each dimension.

In [2]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


# NumPy Array Reshaping

In [4]:
# Reshaping means changing the shape of an array.

In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [6]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# NumPy Array Iterating

In [7]:
# Iterating means going through elements one by one.


In [8]:
import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [9]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [10]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [11]:
# Iterating Arrays Using nditer()

# The function nditer() is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration, lets go through it with examples.

In [12]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


# NumPy Joining Array

In [13]:
# Joining means putting contents of two or more arrays in a single array.

In [14]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [15]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


# Stacking Along Rows

In [16]:
# NumPy provides a helper function: hstack() to stack along rows.

In [17]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [18]:
# NumPy provides a helper function: vstack()  to stack along columns.

In [19]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


# Stacking Along Height (depth)

In [20]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


# NumPy Splitting Array

In [21]:
# Splitting is reverse operation of Joining.

# Joining merges multiple arrays into one and Splitting breaks one array into multiple.

In [22]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [23]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [24]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [25]:
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [26]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


# NumPy Searching Arrays

In [28]:
# You can search an array for a certain value, and return the indexes that get a match.

# To search an array, use the where() method.

In [29]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [30]:
# Search Sorted

# There is a method called searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

In [31]:
import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


# NumPy Sorting Arrays

In [32]:
# Sorting means putting elements in an ordered sequence.

In [33]:
import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))


[0 1 2 3]


In [34]:
import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [35]:
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


# Random Numbers in NumPy

In [36]:
# Random number does NOT mean a different number every time. Random means something that can not be predicted logically.

In [37]:
from numpy import random

x = random.randint(100)

print(x)


4


In [38]:
from numpy import random

x=random.randint(100, size=(5))

print(x)

[34 76 80 20 80]


In [39]:
# The rand() method also allows you to specify the shape of the array.

In [40]:
from numpy import random

x = random.rand(5)

print(x)

[0.1367574  0.20844998 0.05506051 0.00924023 0.23842205]


In [41]:
from numpy import random

x = random.rand(3, 5)

print(x)

[[0.87436761 0.66564751 0.22901212 0.27494819 0.55478001]
 [0.78056961 0.12245252 0.52920595 0.83193634 0.41714431]
 [0.9416128  0.702343   0.73600465 0.60549899 0.11052792]]


In [42]:
# The choice() method allows you to generate a random value based on an array of values.

In [43]:
from numpy import random

x = random.choice([3, 5, 7, 9])

print(x)

5


# numpy.append() in Python

In [44]:
# The numpy.append() function is available in NumPy package. As the name suggests, append means adding something.

In [45]:
import numpy as np  
a=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])  
b=np.array([[11, 21, 31], [42, 52, 62], [73, 83, 93]])  
c=np.append(a,b)  
print(c)

[10 20 30 40 50 60 70 80 90 11 21 31 42 52 62 73 83 93]


In [46]:
import numpy as np  
a=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])  
b=np.array([[11, 21, 31], [42, 52, 62], [73, 83, 93]])  
c=np.append(a,b,axis=0)  
print(c)

[[10 20 30]
 [40 50 60]
 [70 80 90]
 [11 21 31]
 [42 52 62]
 [73 83 93]]


# numpy.sum() in Python

In [47]:
# The numpy.sum() function is available in the NumPy package of Python. 
# This function is used to compute the sum of all elements, the sum of each row, and the sum of each column of a given array.

In [48]:
import numpy as np
a = np.array([0.4,0.5])
b = np.sum(a)
print(b)

0.9


In [49]:
import numpy as np  
a=np.array([[1,4],[3,5]])  
b=np.sum(a)  
print(b) 

13


# numpy.zeros() in Python

In [50]:
# The numpy.zeros() function is one of the most significant functions which is used in machine learning programs widely. 
# This function is used to generate an array containing zeros.

In [51]:
import numpy as np  
a=np.zeros(6)  
print(a)

[0. 0. 0. 0. 0. 0.]


In [53]:
import numpy as np  
a=np.zeros((6,2))
print(a)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


# numpy.Ones() in Python

In [54]:
# The ones tool returns a new array with a given shape and type filled with 1‘s.

In [55]:
import numpy as np  
a=np.ones(6)  
print(a)

[1. 1. 1. 1. 1. 1.]
